<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="cristiano-PC" name="test.persistence.PersonRepositoryTest" tests="6" failures="1" timestamp="22 May 2011 05:36:35 GMT" time="3.67" errors="0">
  <testcase name="testAddPersonRepo" time="0.017" classname="test.persistence.PersonRepositoryTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at test.persistence.PersonRepositoryTest.testAddPersonRepo(PersonRepositoryTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:110)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
    </failure>
  </testcase>
  <testcase name="testFindPersonRepo" time="0.0010" classname="test.persistence.PersonRepositoryTest">
    <skipped/>
  </testcase>
  <testcase name="testCompanyPersistence" time="0.162" classname="test.persistence.CompanyPersistenceTest"/>
  <testcase name="testProductPersistence" time="0.018" classname="test.persistence.CompanyPersistenceTest"/>
  <testcase name="testOperatorPersistence" time="0.021" classname="test.persistence.PersonPersistenceTest"/>
  <testcase name="testUserPersistence" time="0.017" classname="test.persistence.PersonPersistenceTest"/>
</testsuite>
